name: Release to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build wheels
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release --compatibility manylinux2014

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: target/wheels/*

  publish:
    name: Publish to PyPI
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: wheels
          path: dist

      - name: Publish
        uses: PyO3/maturin-action@v1
        with:
          command: publish
          args: --username __token__ --password ${{ secrets.PYPI_TOKEN }} --skip-existing
